canonical/design.ubuntu.com

- _includes/header.html
- _layouts/post-with-banner.html
- audiences/index.md
- brand/colour-palette/index.md
- downloads/index.md
- index.md
- scopes/index.md
- web-style-guide/index.html
- web-style-guide/media/index.md
- web-style-guide/scaffolding/index.md
added a new post-with-banner layout to support the three pages that require it.
> add new layout for banners + syntax errors

- .gitignore
Add css folder to the gitignore folder
Check code
> Add css folder to the gitignore folder

- _includes/footer.html
- _sass/_patterns-font-tester.scss
- assets/js/font.js
- font/index.md
- New content and layout for the /font page
- Rewrote the font testing tool
- `./run`
- [Go to /font](http://localhost:8011/font/)
- Test the font tool and check the page
- [Design](https://www.dropbox.com/work/00_web_team/_design.ubuntu.com/Font%20page/Exports?preview=001+I+Fonts+page+-+final+designs.jpg)
- [Copydoc](https://docs.google.com/document/d/1KeJYwl7Cu4kMYo2X3oiwmYn0hb_D-NTA0NcCAVAET_k/edit#)
Fixes #29 
http://design.ubuntu.com-font.demo.haus/font/
> Update the font page. New content and font sample tool.

- index.md
Updated the homepage content.
./run and check the homepage against the [copydoc](https://docs.google.com/document/d/1vIsFwNOjFu3E-_RPDi6ArArDSMHbYaWSTmy0BmKLhS0/edit#)
Fixes #60
> Update homepage content

- brand/pictograms/index.md
Made pictogram copy match the live site
- ./run
- Navigate to [the pictogram page](http://localhost:8011/brand/pictograms/)
- Compare with [live](http://design.ubuntu.com/brand/pictograms)
Fixes #62
> Pictos: Update page copy

- _includes/footer.html
- _sass/main.scss
- index.md
* set accent background
* updating vertical spacing
* fixed heading sizes
* fixed footer to be full width
* download and `./run` the site
* look at the [homepage](http://0.0.0.0:8011/)
Fixes #22
> fix-up the homepage

- _includes/footer.html
- assets/global-nav
- package.json
- yarn.lock
Add the global-nav npm dep and integrated it into the site
- Pull this branch
- Run `./run clean`
- Run `./run`
- Go to http://0.0.0.0:8011/
- Check that the global nav is there and working
> Add and integrate the npm global navigation component

- _includes/google-analytics.html
- _includes/google-tag-manager.html
- _includes/head.html
- _includes/header.html
* removed google analytics code
* added GTM code
* pull this branch
* run the site
* see that GTM is installed
> Add google tag manager and replacing google analytics code

- nginx.conf
Fixes #103
QA
--
``` bash
$ docker build --build-arg COMMIT_ID=`git rev-parse HEAD` --tag design .
$ docker run --name throwaway --publish 8094:80 design
$ curl -I http://localhost:8094/apps | grep 'Location'
Location: https://docs.ubuntu.com/phone/en/apps/index
$ curl -I http://localhost:8094/apps/subpath | grep 'Location'
Location: https://docs.ubuntu.com/phone/en/apps/index
$ curl -I http://localhost:8094/scopes | grep 'Location'
Location: https://docs.ubuntu.com/phone/en/scopes/index
$ curl -I http://localhost:8094/scopes/subpath | grep 'Location'
Location: https://docs.ubuntu.com/phone/en/scopes/index
$ docker rm -f throwaway
```
> Add redirects for apps and scopes

- _data/downloads.yaml
Added snapcraft logo pack to the downloads page
> Added snapcraft logo pack to the downloads page

- brand/index.md
Fix aspect ratio of laptop image on `/brand`
Go to <http://0.0.0.0:8011/brand/> and make sure the laptop image isn't squashed out of proportion
Fixes #113
> Fix aspect ratio of image

- _includes/footer.html
- _layouts/web-guidelines.html
- web-original/forms/index.md
> Update footer link for bug reporting

- _includes/footer.html
- _includes/nav-brand.html
- _layouts/post.html
- _sass/main.scss
- brand/index.md
- font/index.md
- package.json
- yarn.lock
Upgraded the site to Vanilla 1.8
- ./run
- Check the site in-browser at http://0.0.0.0:8011/
- Compare it to the live site and see that it is the same or better
> Vanilla 1.8

- _includes/footer.html
Updated the footer: 
1. the date of the copyright
2. add a link to u.c/legal
[List of steps to QA the new features or prove the bug has been resolved]
Fixes #142
> Update footer links

- .dockerignore
- Dockerfile
- nginx.conf
- package.json
- yarn.lock
Multistage builds to decrease image size based on ubuntu.com
- Build the image: `docker build --tag myimage --build-arg BUILD_ID=myfakeid .`
- Once image is built, `docker run -ti -p 8111:80 myimage`
- Check site is running smoothly at http://localhost:8111
- Check new id `myfakeid` is in the headers `curl -I http://localhost:8111`
Fixes #152
> Multi-stage builds

- deploy/site.yaml
> Add domain [www.]ubuntu.ai

- Dockerfile
Change dockerfile to use build-js instead of copy-js
Wait for the demo and check the site works
> Change dockerfile to use build-js instead of copy-js

- font/index.md
Check the word "Web" is no longer in the link.
_There doesn't seem to be any copy docs for this site_
- Check the code
Fixes https://github.com/canonical-web-and-design/design.ubuntu.com/issues/191
> Swap Google Web Fonts for Google Fonts

- Dockerfile
Switch from node-slim to node
- Grab master and run `docker build --build-arg TALISKER_REVISION_ID=test --tag design-site .`
- See it fails
- Switch to this branch and run `docker build --build-arg TALISKER_REVISION_ID=test --tag design-site .`
- See that is passed.
> Switch from node-slim to node

- sass/_pattern_font-tester.scss
- sass/main.scss
- templates/font/index.html
* removed unused scss
* simplified the font tester a bit
> cleanup scss WD-1346

- _data/logos.yaml
- redirects.yaml
- requirements.txt
- sass/_pattern_font-tester.scss
- sass/main.scss
- templates/_layouts/_root.html
- templates/_layouts/page.html
- templates/resources/index.html
- webapp/app.py
- Moved `/downloads` to `/resources`
- Implemented the new design for the resources page
- Open the website.
- Navigate to `/resources`.
- Compare it with the design.
- [WD-1297](https://warthogs.atlassian.net/browse/WD-1297)
[WD-1297]: https://warthogs.atlassian.net/browse/WD-1297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-1297 build new resources page

- templates/_layouts/_root.html
- templates/_layouts/page-bare.html
- templates/_layouts/page.html
- templates/accessibility/index.html
- templates/contribute/index.html
- templates/index.html
- templates/resources/index.html
* added new placeholder for home page
> add new home, accessibility and contribute placeholders WD-1300 WD-1344

- Dockerfile
- requirements.txt
* updated flask-base and ubuntu base image
> update flask-base and ubuntu base image

- templates/accessibility/index.html
* added content for a11y page (took most from vanilla docs)
> Update a11y content

- templates/accessibility/index.html
- templates/contribute/index.html
- templates/index.html
* reduce amount of boxes on home page, align its layout
* iterate on contribute page content
* improve accessibility page layout
> New design iterate home a11y contribute

- package.json
- templates/_layouts/_root.html
- templates/index.html
- yarn.lock
New layout applied to home page.
Demo: https://design-ubuntu-com-273.demos.haus/
> Apply new full width layout to design site home page

- Dockerfile
- requirements.txt
- sass/main.scss
- templates/_layouts/_root.html
- templates/_layouts/page.html
- templates/brand/index.html
- templates/vanilla/index.html
- Added the content for the new brand page
- Updated the footer to include the new navigation
It's pretty early stage and the spacing is all over the place but it's all I could do with the miro wireframes
> Build the first draft of the new brand page WD-1343

- _data/resources.yaml
- templates/accessibility/index.html
- templates/brand/index.html
- templates/contribute/index.html
- templates/font/index.html
- templates/index.html
- templates/resources/index.html
- templates/vanilla/index.html
Removing lorem ipsum and doing some small final tweaks on various pages.
> Copy updates and final tweaks

- _data/resources.yaml
Added LXD and multipass logos to the Resources page.
Check if resources page shows LXD and Multipass logos: https://design-ubuntu-com-289.demos.haus/resources
> Add LXD and Multipass logos

- templates/resources/index.html
I updated the mascot wallpaper link to the generic Google drive folder as well as updated the link text
> updated the mascot wallpaper link

- templates/font/index.html
Remove redundant `". "`
Before
` weight and width axes. . Its fixed-width companion`
After:
` weight and width axes. Its fixed-width companion`
https://github.com/canonical/design.ubuntu.com/issues/290
> #290 Remove second "." and space

- templates/accessibility/index.html
Fixes a broken link to accessibility resources.
[List of steps to QA the new features or prove the bug has been resolved]
See https://github.com/canonical/vanilla-framework/pull/5020
> Update link to Accessibility Alphabet
