canonical/design.ubuntu.com

index.md

* Remove 'get inspired' section from homepage
* some html tidy-ups
1. ./run serve -w
2. look at the [homepage](http://0.0.0.0:8011/) or [demo](http://design.ubuntu.com-vbt-updates.demo.haus/)
Fixes #7 and [launchpad bug 1538131]https://bugs.launchpad.net/ubuntu-brand-guidelines/+bug/1538131

Remove 'get inspired' section from homepage

---

_includes/side-nav-brand.html
_layouts/post.html
_sass/_pattern_frame.scss
_sass/_pattern_side-nav.scss
_sass/main.scss
brand/index.md

- Updated brand page. 
- Added some new patterns to style the brand section. 
- Modified core templates to suit the new style.
- Go to `/brand/`
- Compare with [design](https://www.dropbox.com/work/00_web_team/_design.ubuntu.com/Brand%20page/Exports?preview=001+Brand-assets+page.jpg)
- Check that the left-hand nav works and that all pages now have it
[Demo](http://design.ubuntu.com-brand.demo.haus/brand/)

Update brand page. Add some new patterns to style the brand section. Modify core templates to suit the new style.

---

_config.yml

Prevent Jekyll building test files in some cases and throwing this error:
```
Configuration file: ...
Source: ...
Destination: ...
Incremental build: enabled
Generating...
ERROR: YOUR SITE COULD NOT BE BUILT:
------------------------------------
Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/ruby/2.0.0/gems/jekyll-3.4.0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
```
./run should still work correctly (Or the demo below)

Remove vendor/bundle to avoid building Jekyll tests

---

brand/photography-products/index.md

Removed into
- ./run
- Go to [the product photography page](http://localhost:8011/brand/photography-products/)
- See that the intro is removed like on [live](http://design.ubuntu.com/brand/photography-products)
Fixes #63

Remove old product photography intro

---

_includes/side-nav-downloads.html
_layouts/post.html

Updated the list of filters at on the left-hand side of the dowloads page.
*Note*: This is just an update of the page content and the correct grid placement. The full design update will be done as part of the vanilla upgrade (to utilise the new patterns) and the tagging of the design assets will be done when we update the assets closer to launch.
- ./run
- View the [download page](http://localhost:8011/downloads/) and see that, although not well designed, the correct [download filters](https://docs.google.com/document/d/1QIUUzAxF1Musm7LfKNO_Cvx3vpuqJM-QZozDKznivhs/edit) are present
Fixes #44

Update the download page sorting options

---

_sass/main.scss
package.json
yarn.lock

* updated to vanilla 1.5.1 and removed the brochure theme
* `./run serve` and see that vanilla is running
* check mail.css and see that the  p-accordian (a recent pattern) is in it
Partly fixes #40

Update to the vanilla 1.5.1

---

404.html
Dockerfile
nginx.conf

- Add Dockerfile for building web app image
- Driveby: Add a 404 page
Fixes #93 
QA
--
Build and run the docker image:
``` bash
docker build --tag design-site --build-arg COMMIT_ID=`git rev-parse HEAD` .
docker run -p 80:80 design-site
```
Go to <http://127.0.0.1> and see the design site in all its glory. Go to <http://127.0.0.1/nonsense> and see a 404 page.

Add Dockerfile

---

Dockerfile

Provide the ID of the commit at which point the code was built, as a HTTP header in the response from the docker container.
For production - so we can easily see which version of the code is running on a unit.
QA
--
``` bash
$ docker build .  # Check it complains without COMMIT_ID
The command '/bin/sh -c test -n "${COMMIT_ID}"' returned a non-zero code: 1
$ docker build --tag design --build-arg COMMIT_ID=`git rev-parse HEAD` .  # Build with COMMIT_ID
$ docker run --rm --name design-throwaway --daemonize --publish 8097:80 design
$ curl -I localhost:8097 | grep 'X-'
X-commit-ID: 018f47199c3709e9d0bceb33bef30546ee76e820
X-Hostname: 096dbd5ae462
$ docker kill design-throwaway
```

Make COMMIT_ID mandatory

---

brand/illustration/index.md
brand/ubuntu-logo/index.md

Fix link to colour palette 
- Go to <http://0.0.0.0:8011/brand/ubuntu-logo/> and see that the `colours section` link doesn't lead to a 404
- Go to <http://0.0.0.0:8011/brand/illustration/> and see that the `More about the colour palette` link doesn't lead to a 404
Fixes #112

Fix link to colour palette

---

_includes/footer.html

- Add a data privacy link to the footer
- Run the site
- See there is a link to https://www.ubuntu.com/legal/data-privacy in the footer

Add data privacy link to the footer

---

font/index.md

- Updated font download links to point to new versions of the zip file, which now includes Ubuntu thin
- Check out this feature branch
- Run the site using the command ./run serve
- View the site locally in your web browser at: [/font](http://0.0.0.0:8011/font)
- In the resources section at the bottom of the page, click "Download the Ubuntu Font Family", "Download the Ubuntu Font Family source code" and the orange "Download for free" CTA, and ensure all three files contain `Ubuntu-Th.ttf`
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1141

1141: update font download links to assets that include ubuntu thin

---

Dockerfile
renovate.json

Downgrade to ruby 2.5
Disable renovate in docker
- `DOCKER_BUILDKIT=1 docker build --build-arg BUILD_ID=test --tag design.ubuntu.com .`
- `docker run -ti -p "8006:80" --env SECRET_KEY=secret_key design.ubuntu.com`
- http://localhost:8006 play around

Revert to ruby 2.5

---

nginx.conf

Fixes https://github.com/canonical-web-and-design/design.ubuntu.com/issues/158
- `DOCKER_BUILDKIT=1 docker build --build-arg BUILD_ID=test --tag design.ubuntu.com .`
- `docker run -ti -p "8006:80" --env SECRET_KEY=secret_key design.ubuntu.com`
- Make sure that `http://localhost:8006/font/ufl` redirects to https://ubuntu.com/legal/font-licence

Add rewrite rule for legal fonts

---

_data/downloads.yaml

Change the download size for *Premier cloud partner logo set* file because it appears to be far more smaller than what was originally listed on the website
1. Start the site
2. Navigate to http://localhost:8001/downloads/
3. Scroll down until *Premier cloud partner logo set*
4. A new, fixed, file size should appear, and not something like this:
N/A. I originally wanted to make an issue but then I decided to just modify the problematic file and then make this pull request

Fix file size/typo

---

package.json
yarn.lock

- Bump cookie policy to v3.03
- Update GTM to track initial pageview
1. Check out this feature branch
2. Run the site using the command ./run serve
3. View the site locally in your web browser at: http://0.0.0.0:8011
4. See that you are using cookie policy 3.03

Bump cookie policy to v3.03

---

font/index.md

Fixed a typo in a reference to the DejaVu font project
N/A
N/A

Fix project name (“DejaVu”, not “Deja”)

---

_includes/footer.html

Removed redundant argument from globalNav initialiser call.
- Visit https://design-ubuntu-com-240.demos.haus/
- See that the "All Canonical" item is present in the nav, and the dropdown works

remove unused argument from globalNav init

---

assets/js/font.js
sass/_pattern_font-tester.scss

Now:
- Font weight options stay disabled when trying different font weights
- When orange is selected as the font colour, the text turns ubuntu-orange instead of a very dark grey
- Run site
- On `/font` page:
1. Select _Ubuntu Condensed_ as Family
2. Select a different Weight
3. See that the invalid Weight options are disabled
4. Select again a Weight
5. See that the invalid Weight options are still disabled
6. Select _Orange_ as Color
7. See that the colour of the text is orange
As the orange colour scss variable `$color-brand` was defined in [vanilla-framework](/canonical/vanilla-framework) 's [_settings_colors.scss](/canonical/vanilla-framework/blob/main/scss/_settings_colors.scss#L185), I changed it to the correct (orange) variable in the [same …

Fixed font selection

---

font/index.md

- Removes a inline styled white background from a textarea based on advice from Lyubo.
- Go to /font and check the text area has the latest vanilla style.

Removes white background onn text area

---

templates/404.html
templates/accessibility/index.html
templates/contribute/index.html
templates/font/index.html
templates/index.html
templates/resources/index.html

- Use the new layout on the following pages:
- Home
- Accessibility
- Contribute
- Font
- Resources
- 404
- Minor fixes on the resources page
- Remove the Illustration section
- Make the Icon set section dark mode switch hide on medium and small screens
- Open the site and inspect the pages for the new layout
- Navigate to `/resources` 
- Check if the icon set switch hides on medium and small screens
- Check that the illustration section has been removed
- [WD-1299](https://warthogs.atlassian.net/browse/WD-1299)
- [WD-1297](https://warthogs.atlassian.net/browse/WD-1297)
[WD-1299]: https://warthogs.atlassian.net/browse/WD-1299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WD-1297]: https://warthogs.atlassian.net/browse/WD-1297?atlOrigin=eyJpIj …

WD-1299 use new vanilla layout on design ubuntu com site

---

templates/resources/index.html

Removes link to internal google drive with logos.
Go to [Resources](https://design-ubuntu-com-282.demos.haus/resources) page. There should be no link below logos to google drive.

Remove internal google drive link

---

.prettierignore
_data/resources.yaml
sass/main.scss
templates/_layouts/_root.html
templates/resources/index.html

Updated logos on resources page with new stacked ones.
Fixes WD-3039
- Go to resources page: https://design-ubuntu-com-287.demos.haus/resources
- make sure logos are updated to new versions

Update logos on resources page to new stacked ones

---

templates/_layouts/_root.html
templates/font/index.html

Makes sure all static resources are versioned to avoid cache issues.
- Go to demo, make sure it displays correctly (https://design-ubuntu-com-288.demos.haus/)
- Inspect the page, make sure static resources use versioned URLs

Use versioned links to static resources

---

templates/resources/index.html

Fixes [WD-5433](https://warthogs.atlassian.net/browse/WD-5433)
- Go to [Resources page](https://design-ubuntu-com-294.demos.haus/resources)
- Make sure Wallpaper section is there
- Make sure link to wallpapers folder works (and is public)
[WD-5433]: https://warthogs.atlassian.net/browse/WD-5433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add wallpaper section to Resources page

---

templates/resources/index.html

updated the wallpaper thumbnail from Lunar to Mantic

updated thumbnail for wallpaper

---

sass/main.scss

Fix dark mode's background
Go to /resources and enable dark mode
https://warthogs.atlassian.net/browse/WD-6233

Update resource's dark mode's background

---

.github/workflows/pr.yaml

Version 10.3 of linkchecker throws warnings on redirects and fails the build (https://linkchecker.github.io/linkchecker/upgrading.html#migrating-from-10-2-to-10-3).
This PR ignores linkchecker redirect warnings to prevent them from failing the CI.
- make sure linkchecker CI job passes

Ignore warnings to prevent failing build

---

sass/main.scss
templates/resources/_email-signature.html
templates/resources/index.html

Adds email signature to design resources.
Drive-by: update slide template preview
Fixes [WD-9907](https://warthogs.atlassian.net/browse/WD-9907)
Fixes [WD-4140](https://warthogs.atlassian.net/browse/WD-4140)
- Go do [resources page](https://design-ubuntu-com-311.demos.haus/resources), scroll down to email signature
- Edit details in place if you want to
- Select the signature and copy it
- Go to Gmail
- compose new email, paste signature into the email
- or go to Gmail / Settings / Signature and paste it as a signature
[WD-9907]: https://warthogs.atlassian.net/browse/WD-9907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WD-4140]: https://warthogs.atlassian.net/browse/WD-4140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIj …

Add email signature to design resources

---

templates/resources/_email-signature.html

Removed unnecessary empty link from email signature template
- https://design-ubuntu-com-312.demos.haus/resources
- Check if email signature renders fine without the link around email address

Remove unnecessary link from email signature template

---

templates/resources/index.html

Updates the duplicated id and replaces it with a `#email-signature` id, so that email signature section can be targeted in URL.
Fixed issue reported in https://github.com/canonical/design.ubuntu.com/pull/311#issuecomment-2025462261
Go to demo resources page using direct link to email section, make sure the page loads scrolled down:
https://design-ubuntu-com-314.demos.haus/resources#email-signature

Fix the id of email signature section on Resources page

---

templates/resources/index.html

Removes editing option from email signature template, because it was confusing and too easy to mess up then trying to select (by dragging the image).
Go to: https://design-ubuntu-com-315.demos.haus/resources#email-signature
Make sure email signature can be selected but is not editable.

Remove editing from email signature

---

templates/_layouts/_root.html
templates/accessibility/index.html
templates/brand/index.html
templates/contribute/index.html
templates/font/index.html
templates/index.html
templates/resources/index.html
templates/vanilla/index.html

Add the copydoc meta header to the site
Add the two copydocs we have
1. Open the demo
2. Check you see the copydoc extension show up
3. Check homepage and font pages to load a copy doc
4. Other pages should open the folder

Add the copydoc meta header to the site

---

templates/vanilla/index.html

Adds more links to Vanilla website from Design System Vanilla page.
Fixes: https://warthogs.atlassian.net/browse/WD-12518
- go to Vanilla page: https://design-ubuntu-com-318.demos.haus/vanilla
- check if you find links to Vanilla home page, docs and github

Add more Vanilla links to Vanilla page

---

_data/resources.yaml

- Add microcloud logo in the list of logos on `https://design.ubuntu.com/resources`
- go to `/resources` and check that the microcloud logo is added at the bottom
https://warthogs.atlassian.net/browse/WD-14922

Add microcloud logo (WD-14922)

---

templates/resources/index.html

Removes internal slides from resources page
Fixes https://warthogs.atlassian.net/browse/WD-14508
Check the [updated resources page](https://design-ubuntu-com-325.demos.haus/resources), make sure slides are not listed there anymore. (compare with [live version](https://design.ubuntu.com/resources)).

Remove internal slides from the resources page

---

package.json
templates/_layouts/_root.html
yarn.lock

- Move cookie policy before GTM
- Go to demo
- Open dev tools and go to Networks tab
- Check that the cookie policy finishes its updates before GTM script invoked
Fixes [WD-15451](https://warthogs.atlassian.net/browse/WD-15451) and [WD-15825](https://warthogs.atlassian.net/browse/WD-15825)
[if relevant, include a screenshot]
[WD-15451]: https://warthogs.atlassian.net/browse/WD-15451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WD-15825]: https://warthogs.atlassian.net/browse/WD-15825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Invoke cookie policy before gtm

---

templates/resources/index.html
templates/vanilla/index.html

- Updated link of Figma library to the latest link
- Removed link to Sketch library (I assumed we don't want to link to this outdated library anymore?)
- check the links work as expected

Update Figma library link

---

templates/resources/_email-signature.html
templates/resources/index.html

- Replace email signature 20 year logo with the standard Canonical logo
- Navigate to [/resources](https://design-ubuntu-com-331.demos.haus/resources) and make sure the logo is replaced accordingly.
- [WD-18640](https://warthogs.atlassian.net/browse/WD-18640)
Before:
After:
[WD-18640]: https://warthogs.atlassian.net/browse/WD-18640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-18640 - Feat: switch email signature to user standard Canonical logo and add additional fields

---

templates/resources/_email-signature.html

- Replace the email signature logo
- Copy the email signature and send a test email.
- Make sure the logo shows after the email is sent.
- [WD-18640](https://warthogs.atlassian.net/browse/WD-18640)
[WD-18640]: https://warthogs.atlassian.net/browse/WD-18640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: resolve logo not showing after email is sent
